name: 🧪 Build · Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - '.github/workflows/build-and-test.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build and run tests
        run: npm run build:test && npm run test
