name: update_version

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Authenticate to NPM registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Clean Git working directory
        run: |
          git reset --hard
          git clean -fd

      - name: Configure git
        run: |
          git config --local user.email "kscodebase@gmail.com"
          git config --local user.name "kakasoo"

      - name: Build and run tests
        run: npm run build:test && npm run test

      - name: Production build
        run: npm run build

      - name: Bump version
        run: npm version patch

      - name: Publish to NPM
        run: npm publish

      - name: Push changes to repository
        run: |
          git push --set-upstream origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
